//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploi
    {
        public int idEmploi { get; set; }
        public System.DateTime dateEntree { get; set; }
        public Nullable<System.DateTime> dateSortie { get; set; }
        public string soumis { get; set; }
        public decimal numeroEntreprise { get; set; }
        public decimal codeProfession { get; set; }
        public int idPersonne { get; set; }
    
        public virtual Personne Personne { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Entreprise Entreprise { get; set; }
    }
}
