//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploi
    {
        public int idEmploi { get; set; }
        public System.DateTime dateEntree { get; set; }
        public Nullable<System.DateTime> dateSortie { get; set; }
        public string soumis { get; set; }
        public decimal numeroEntreprise { get; set; }
        public decimal codeProfession { get; set; }
        public decimal idPersonne { get; set; }
    
        public virtual Personne Personne { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Entreprise Entreprise { get; set; }
    }
}
