//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipeMed
    {
        public decimal idEquipe { get; set; }
        public string idAssistante1 { get; set; }
        public string idAssistante2 { get; set; }
        public decimal idLieu1 { get; set; }
        public decimal idLieu2 { get; set; }
        public decimal idLieu3 { get; set; }
    }
}
