//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBIG3B4Entities : DbContext
    {
        public DBIG3B4Entities()
            : base("name=DBIG3B4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entreprise> Entreprises { get; set; }
        public virtual DbSet<EquipeMed> EquipeMeds { get; set; }
        public virtual DbSet<Langue> Langues { get; set; }
        public virtual DbSet<Lieu> Lieux { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Secteur> Secteurs { get; set; }
        public virtual DbSet<tradTravail> tradTravails { get; set; }
        public virtual DbSet<Emploi> Emplois { get; set; }
    }
}
