//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tradTravail
    {
        public decimal idTradTravail { get; set; }
        public string traduction { get; set; }
        public decimal codeProfession { get; set; }
        public decimal codeLangue { get; set; }
    
        public virtual Langue Langue { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
